Prevent error when click event has no data params
This has been preventing users for clicking things due to:
NoMethodError: undefined method 'permit' for nil:NilClass