(fix) Latest Docker version requires a container name to be set
After updating to the latest version of Docker (Docker version 18.09.0, build 4d60db4) I had an issue where Docker could not find the web container:

```
Error: No such container: teacher-vacancy-service_web_1
```

Specifying the container name in `docker-compose.yml` has resolved this.