Update README.md
This is because I had the following issue:

> brew update --cask chromedriver

Error: This command updates brew itself, and does not take formula names.
Use brew upgrade --cask chromedriver instead.