Fix jobseeker profile bug (#8797)
## Trello card URL
https://trello.com/c/AUkAlDT5/2852-jobseeker-profile-job-preferences-bug

## Changes in this PR:

This PR fixes a `NoMethodError: undefined method 'join' for nil `crash
for jobseekers who have subjects set to nil but have the subjects step
marked as completed. Also fixes invalid `</br>` used to join locations,
replacing it with tag.br, which was needed to allow us to use safe_join
to safely handle nil values.

## Screenshots of UI changes:

### Before

### After


## Checklists:

### Data & Schema Changes

If this PR modifies data structures or validations, check the following:

- [ ] Adds/removes model validations
- [ ] Adds/removes database fields
- [ ] Modifies Vacancy enumerables (phases, working patterns, job roles,
key stages, etc.)

<details>
<summary>If any of the above options has changed then the author must
check/resolve all of the following...</summary>

### Integration Impact

Does this change affect any of these integrations?
- [ ] DfE Analytics platform
- [ ] Legacy imports mappings
- [ ] DWP Find a Job export mappings
- [ ] Publisher ATS API (may require mapping updates or API versioning)

### User Experience & Data Integrity

Could this change impact:
- [ ] Existing subscription alerts (will legacy subscription search
filters break?)
- [ ] Legacy vacancy copying (will copied vacancies fail new
validations?)
- [ ] In-progress drafts for Vacancies or Job Applications
</details>